FROM python:2.7

WORKDIR /app

ADD requirements.txt /app/requirements.txt
RUN pip install -r requirements.txt
RUN pip install nose
#ADD run.py /app/run.py
ADD . /app
EXPOSE 4200
WORKDIR /app

CMD ["python", "run.py"]
